// <auto-generated />
using Catedraticoapi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catedraticoapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211115013142_agregarcatedratico")]
    partial class agregarcatedratico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Catedraticoapi.Models.Catedratico", b =>
                {
                    b.Property<int>("Idcatedratico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcatedratico");

                    b.ToTable("Catedraticos");
                });

            modelBuilder.Entity("Catedraticoapi.Models.Curso", b =>
                {
                    b.Property<int>("Idcurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Punteo")
                        .HasColumnType("int");

                    b.HasKey("Idcurso");

                    b.ToTable("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
